kSemiOnlyWeapons = {
  -- Pistols
  "WEAPON_PISTOL",
  "WEAPON_SNSPISTOL",
  "WEAPON_VINTAGEPISTOL",
  "WEAPON_COMBATPISTOL",
  "WEAPON_HEAVYPISTOL",
  "WEAPON_PISTOL50",
  "WEAPON_MARKSMANPISTOL",
  "WEAPON_FLAREGUN",
  -- Shotguns
  "WEAPON_PUMPSHOTGUN",
  "WEAPON_SAWNOFFSHOTGUN",
  "WEAPON_BULLPUPSHOTGUN",
  -- SMGs
  "WEAPON_MICROSMG",
  "WEAPON_MINISMG",
  "WEAPON_SMG",
  "WEAPON_COMBATPDW",
  "WEAPON_ASSAULTSMG",
  -- Assault Rifles
  "WEAPON_COMPACTRIFLE",
  "WEAPON_ASSAULTRIFLE",
  "WEAPON_CARBINERIFLE",
  "WEAPON_SPECIALCARBINE",
  "WEAPON_BULLPUPRIFLE",
  "WEAPON_ADVANCEDRIFLE",
}